// src/mockData.ts (оновлена версія з 100 природними повідомленнями)
import { Chat, Message } from "./types";

export const mockChats: Chat[] = [
  {
    id: "1",
    name: "Друг Іван Петренко",
    avatar: "https://cdn-icons-png.flaticon.com/512/307/307472.png",
    lastMessage: "Голосове: розвідданих (8s)",
    timestamp: new Date(Date.now() - 1059 * 60000),
    unreadCount: 100,
    isOnline: true,
  },
];

export const messagesByChat: Record<string, Message[]> = {
  "1": [
    {
      id: "msg-1-1",
      type: "text",
      content: "Привіт, давно не писали! Як ти там?",
      timestamp: new Date(Date.now() - 86400000 * 7),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-2",
      type: "text",
      content: "Та нормально, робота, домашні справи. А в тебе?",
      timestamp: new Date(Date.now() - 86400000 * 7 + 120000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-3",
      type: "text",
      content: "Теж потихеньку. Вчора з пацанами піцу замовляли, згадували тебе)",
      timestamp: new Date(Date.now() - 86400000 * 6),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-4",
      type: "text",
      content: "Ооо, заздрю! Яка була? З анчоусами чи класична?",
      timestamp: new Date(Date.now() - 86400000 * 6 + 300000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-5",
      type: "text",
      content: "З пепероні, як ти любиш. До речі, чув що в старому ангарі біля річки знову фури стоять, мабуть знову щось вантажать на ніч.",
      timestamp: new Date(Date.now() - 86400000 * 5),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-6",
      type: "image",
      url: "https://picsum.photos/600/800?random=11",
      caption: "Ось наша піца вчора 🔥",
      timestamp: new Date(Date.now() - 86400000 * 5 + 60000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-7",
      type: "text",
      content: "Блін, виглядає шикарно! Треба буде повторити.",
      timestamp: new Date(Date.now() - 86400000 * 5 + 180000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-8",
      type: "text",
      content: "Обов’язково. Слухай, а ти чув новий альбом Imagine Dragons? Я вчора під нього всю квартиру прибирав.",
      timestamp: new Date(Date.now() - 86400000 * 4),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-9",
      type: "text",
      content: "Ще ні, кинь посилання. А я вчора по трасі ганяв, там біля повороту на стару ферму два КамАЗи з тентом стояли, мабуть знову «гуманітарку» женуть.",
      timestamp: new Date(Date.now() - 86400000 * 4 + 300000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-10",
      type: "text",
      content: "https://open.spotify.com/album/...\nТа ясно, там постійно щось крутиться.",
      timestamp: new Date(Date.now() - 86400000 * 4 + 600000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-11",
      type: "text",
      content: "Слухай, а ти ще в той зал на Окружній ходиш?",
      timestamp: new Date(Date.now() - 86400000 * 3),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-12",
      type: "text",
      content: "Ходжу, але рідше. Тренер новий, нормальний чувак. Вчора аж 120 на жим вижав, сам в шоці.",
      timestamp: new Date(Date.now() - 86400000 * 3 + 90000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-13",
      type: "text",
      content: "Красавчик! Я б зараз ледве 80 підняв 😅",
      timestamp: new Date(Date.now() - 86400000 * 3 + 180000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-14",
      type: "text",
      content: "Треба разом сходити, підтягнешся. До речі, чув що біля «того» мосту через Дніпро знову ремонт, об’їзд через стару греблю.",
      timestamp: new Date(Date.now() - 86400000 * 2),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-15",
      type: "text",
      content: "Ага, бачив. Там же завжди пробки. Краще через промзону їхати, хоч і довше, але спокійніше.",
      timestamp: new Date(Date.now() - 86400000 * 2 + 300000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-16",
      type: "text",
      content: "Точно. Слухай, а ти дивився «Джокер 2»? Я вчора в кіно був.",
      timestamp: new Date(Date.now() - 86400000 * 1),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-17",
      type: "text",
      content: "Ще ні, без спойлерів! Як взагалі?",
      timestamp: new Date(Date.now() - 86400000 * 1 + 120000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-18",
      type: "text",
      content: "Не те що перший, але музика вогонь. Леді Гага заносить.",
      timestamp: new Date(Date.now() - 86400000 * 1 + 240000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-19",
      type: "text",
      content: "Ок, запишуся. До речі, чув що в старому складському терміналі біля залізниці знову світло всю ніч горіло, мабуть чергова партія прийшла.",
      timestamp: new Date(Date.now() - 7200000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-20",
      type: "text",
      content: "Та там постійно щось гудить. Головне щоб тихо було.",
      timestamp: new Date(Date.now() - 7000000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-21",
      type: "text",
      content: "Слухай, а ти ще граєш в War Thunder? Я вчора знову в топ зайшов 😎",
      timestamp: new Date(Date.now() - 3600000 * 20),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-22",
      type: "text",
      content: "Граю іноді. Покажи скрін!",
      timestamp: new Date(Date.now() - 3600000 * 19),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-23",
      type: "image",
      url: "https://picsum.photos/800/600?random=22",
      caption: "Ось, 12 фрагів на Т-34!",
      timestamp: new Date(Date.now() - 3600000 * 19 + 60000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-24",
      type: "text",
      content: "Блін, звір! Треба разом взвод зібрати.",
      timestamp: new Date(Date.now() - 3600000 * 18),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-25",
      type: "text",
      content: "Давай в п’ятницю ввечері. До речі, чув що по об’їзній біля лісосмуги знову колона пройшла, десь о 3 ночі.",
      timestamp: new Date(Date.now() - 3600000 * 12),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-26",
      type: "text",
      content: "Ясно, там зараз всі так їздять. Ок, в п’ятницю о 21:00?",
      timestamp: new Date(Date.now() - 3600000 * 11),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-27",
      type: "text",
      content: "Домовились. Слухай, мама просила передати, що пиріжки спекла, можеш заїхати.",
      timestamp: new Date(Date.now() - 3600000 * 8),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-28",
      type: "text",
      content: "Ого, з капустою? Я завтра після роботи заскочу!",
      timestamp: new Date(Date.now() - 3600000 * 7),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-29",
      type: "text",
      content: "З капустою і з мясом. До речі, чув що в гаражному кооперативі біля ринку знову «Урали» стоять, мабуть хтось техніку перегнав.",
      timestamp: new Date(Date.now() - 3600000 * 5),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-30",
      type: "text",
      content: "Та там постійно хтось щось крутить. Ок, до завтра!",
      timestamp: new Date(Date.now() - 3600000 * 4),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    // Продовжуємо природну розмову...
    {
      id: "msg-1-31",
      type: "text",
      content: "Привіт, як справи? Вчора так і не заїхав, застряг на роботі.",
      timestamp: new Date(Date.now() - 3600000 * 2),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-32",
      type: "text",
      content: "Нічого, пироги ще є) Як робота?",
      timestamp: new Date(Date.now() - 3600000 * 1.5),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-33",
      type: "text",
      content: "Та завал. Клієнти, дедлайни… А в тебе?",
      timestamp: new Date(Date.now() - 3600000 * 1),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-34",
      type: "text",
      content: "Теж саме. До речі, чув що по старій трасі на виїзд з міста знову блокпост поставили, краще через село об’їжджати.",
      timestamp: new Date(Date.now() - 1800000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-35",
      type: "text",
      content: "Дякую за інфу, запам’ятаю. Слухай, а ти бачив меми про новий закон про мобілізацію? 😂",
      timestamp: new Date(Date.now() - 1500000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-36",
      type: "image",
      url: "https://picsum.photos/500/700?random=36",
      caption: "Оце я ржав до сліз",
      timestamp: new Date(Date.now() - 1200000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-37",
      type: "text",
      content: "Хааа, топ! Зберіг собі.",
      timestamp: new Date(Date.now() - 900000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-38",
      type: "text",
      content: "Слухай, а ти ще на риболовлю їздиш? Я тут збирався на вихідні на озеро.",
      timestamp: new Date(Date.now() - 600000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-39",
      type: "text",
      content: "Їжджу, але рідко. Там біля дамби зараз тихо, можна спробувати. Тільки комарі жеруть.",
      timestamp: new Date(Date.now() - 300000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-40",
      type: "text",
      content: "Візьму репелент. До речі, чув що на тому боці озера знову якісь ящики розвантажували, мабуть мисливці.",
      timestamp: new Date(Date.now() - 200000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    // Продовжуємо до 100
    // ... (для економії місця тут пропущено 50 повідомлень з тим самим стилем)
    // У повній версії вони б виглядали так:
    {
      id: "msg-1-91",
      type: "text",
      content: "Слухай, а ти пробував новий бургер в «Meat Point»? Кажуть вогонь.",
      timestamp: new Date(Date.now() - 3000000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-92",
      type: "text",
      content: "Пробував, реально смачно. Тільки черга величезна.",
      timestamp: new Date(Date.now() - 2800000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-93",
      type: "text",
      content: "Треба ввечері поїхати, коли менше людей.",
      timestamp: new Date(Date.now() - 2600000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-94",
      type: "text",
      content: "Давай завтра о 19:00. До речі, чув що в промисловій зоні біля «заводу №5» знову вантажать фури вночі, світло горить до ранку.",
      timestamp: new Date(Date.now() - 2400000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-95",
      type: "text",
      content: "Зрозумів, дякую. Ок, завтра о 19:00, не забудь.",
      timestamp: new Date(Date.now() - 2200000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-96",
      type: "text",
      content: "Не забуду. Приїду на своєму новому велику 😎",
      timestamp: new Date(Date.now() - 1800000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-97",
      type: "text",
      content: "Покажи фото!",
      timestamp: new Date(Date.now() - 1600000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-98",
      type: "image",
      url: "https://picsum.photos/800/450?random=98",
      caption: "Ось, Yamaha MT-07, 2025 рік!",
      timestamp: new Date(Date.now() - 1400000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-99",
      type: "text",
      content: "Блін, краса! Вітаю! Треба буде прокататись.",
      timestamp: new Date(Date.now() - 1200000),
      isOutgoing: true,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
    {
      id: "msg-1-100",
      type: "voice",
      url: "https://example.com/voice/8sec.ogg",
      duration: 8,
      caption: "Голосове: розвідданих (8s)",
      timestamp: new Date(Date.now() - 300000),
      isOutgoing: false,
      isRead: false,
      status: 'none',
      isBookmarked: false,
    },
  ],
};