// src/mockData.ts (оновлена версія з ~100 повідомленнями — умовні координати/плани, без реальних військових даних)
import { Chat, Message } from "./types";

export const mockChats: Chat[] = [
  {
    id: "1",
    name: "Друг Іван Петренко",
    avatar: "https://cdn-icons-png.flaticon.com/512/307/307472.png",
    lastMessage: "Голосове: звіт з точки A (9s)",
    timestamp: new Date(Date.now() - 1059 * 60000),
    unreadCount: 5,
    isOnline: true,
  },
];

export const messagesByChat: Record<string, Message[]> = {
  "1": [
    {
      id: "msg-1-1",
      type: "text",
      content: "Привіт! Давно не бачився — як справи у тебе?",
      timestamp: new Date(Date.now() - 86400000 * 12),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-2",
      type: "text",
      content: "Привіт! Живу. Робота-забава. У тебе як? Плануєш у вихідні щось?",
      timestamp: new Date(Date.now() - 86400000 * 12 + 60000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-3",
      type: "text",
      content: "Думав вибратися на природу — шашлики, музика. Можемо зібрати невелику колону машинами/мото, для настрою 😄",
      timestamp: new Date(Date.now() - 86400000 * 11),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-4",
      type: "text",
      content: "Я за. Пропоную зустрітись біля старого моста, умовно назвемо її Точка A (X12-Y8). Ти як?",
      timestamp: new Date(Date.now() - 86400000 * 11 + 120000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-5",
      type: "text",
      content: "Окей, Точка A — зрозумів. Думаю приїхати на мото. Хочеш, щоб я кинув маршрутик у чат у вигляді умовних координат?",
      timestamp: new Date(Date.now() - 86400000 * 10 + 300000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-6",
      type: "text",
      content: "Кидай, тільки в стислому вигляді: Точка A → Точка B (пікник).",
      timestamp: new Date(Date.now() - 86400000 * 10 + 360000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-7",
      type: "text",
      content: "Ось: Точка A (X12-Y8) — старт; Точка B (X13-Y9) — місце пікніка; орієнтир — великий дуб біля ставка.",
      timestamp: new Date(Date.now() - 86400000 * 9),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-8",
      type: "text",
      content: "Гуд. Думаю заїхати раніше — перевірити комплект гучномовця й гриль. Хто ще їде?",
      timestamp: new Date(Date.now() - 86400000 * 9 + 90000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-9",
      type: "text",
      content: "Маша, Сергій і ще два наших — кажуть їдуть. Вони будуть на фургоні (умовна назва «Фургон-1»), повезуть стільці й мангал.",
      timestamp: new Date(Date.now() - 86400000 * 8 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-10",
      type: "image",
      url: "https://picsum.photos/600/400?random=10",
      caption: "Фото мангала, який збираємось брати — виглядає живуче 🔥",
      timestamp: new Date(Date.now() - 86400000 * 8 + 180000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-11",
      type: "text",
      content: "О, норм. Я візьму рюкзак з посудом і запасом дров. Перевіряй тиск в шинах, доріжки після дощу слизькі.",
      timestamp: new Date(Date.now() - 86400000 * 7 + 120000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-12",
      type: "text",
      content: "Добре. Я вранці прокатую списки — хто що бере. Можеш скинути умовну план-сітку (типа перевірити обладнання, паливо, інструмент)?",
      timestamp: new Date(Date.now() - 86400000 * 7 + 300000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-13",
      type: "text",
      content: "Зроблю. Пункт 1 — бензин/заряд батарей; 2 — запас води; 3 — аптечка; 4 — інструмент/ремонтний набір.",
      timestamp: new Date(Date.now() - 86400000 * 6 + 60000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-14",
      type: "text",
      content: "Чудово. Сергій каже, що «Фургон-1» може під'їхати до Точки A з 10:00. Хочеш, щоб вони чекали 20 хв перед виїздом?",
      timestamp: new Date(Date.now() - 86400000 * 6 + 120000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-15",
      type: "text",
      content: "Так, 10:20 — зручніше. Міші та Максу кину інструкцію по навігатору: вибирайте маршрут через село, мало людей.",
      timestamp: new Date(Date.now() - 86400000 * 6 + 240000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-16",
      type: "text",
      content: "Можеш скинути умовний чек-лист перед виїздом? Просто по пунктах, щоб Міша не забув ремкомплект.",
      timestamp: new Date(Date.now() - 86400000 * 5 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-17",
      type: "text",
      content: "Ок: 1) пальне — мін 3/4 бака; 2) заряджені телефони/паурбанки; 3) аптечка; 4) ремкомплект; 5) тент на випадок дощу.",
      timestamp: new Date(Date.now() - 86400000 * 5 + 180000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-18",
      type: "text",
      content: "Гаразд, кидаю в загальний. Хтось із нас займе на собі роль «координатора» — спостерігати за погодою і змінами? Умовно — роль «Навігатор».",
      timestamp: new Date(Date.now() - 86400000 * 4 + 90000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-19",
      type: "text",
      content: "Я можу. Навігатор на вахті — буду відстежувати трафік та підказувати об'їзди (умовні позначки: Точка C — коротка об’їздна).",
      timestamp: new Date(Date.now() - 86400000 * 4 + 180000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-20",
      type: "image",
      url: "https://picsum.photos/700/400?random=20",
      caption: "Карта умовного району — відмітив Точку A, B, C. Фейкові координати: X12-Y8, X13-Y9, X14-Y7",
      timestamp: new Date(Date.now() - 86400000 * 3 + 60000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-21",
      type: "text",
      content: "Круто, тепер ясно. Пропоную зібратися біля АЗС на в'їзді і вже звідти рушити колоною на Точку A—хто за?",
      timestamp: new Date(Date.now() - 86400000 * 3 + 120000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-22",
      type: "text",
      content: "За. Час збірки умовно 09:30 на АЗС «Швидко». Потім рушаємо хвилями: спочатку Фургон-1, потім дві машини, потім мото.",
      timestamp: new Date(Date.now() - 86400000 * 2 + 300000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-23",
      type: "text",
      content: "Добре. Можна додати правило: дистанція між авто — мін 30 м, щоб не гальмувати один одного. Розумієш про що я?",
      timestamp: new Date(Date.now() - 86400000 * 2 + 360000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-24",
      type: "text",
      content: "Так, логічно. А ще — домовимось по сигналам: два коротких — зупинка, один довгий — увага/повернення. Можеш вкинути це в чат?",
      timestamp: new Date(Date.now() - 86400000 * 2 + 420000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-25",
      type: "text",
      content: "Вкинув. Також запропонував Міші взяти ліхтарі — як запасні для вечірніх посиденьок.",
      timestamp: new Date(Date.now() - 86400000 * 1 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-26",
      type: "text",
      content: "Ок, я ще додам: перевірити ремені кріплення на фургоні — не хочеться, щоб стільці полетіли по дорозі 😅",
      timestamp: new Date(Date.now() - 86400000 * 1 + 150000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-27",
      type: "image",
      url: "https://picsum.photos/600/600?random=27",
      caption: "Фото кріплення — Міша каже, треба ще пару ременів.",
      timestamp: new Date(Date.now() - 86400000 * 1 + 240000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-28",
      type: "text",
      content: "Добре, візьму ремені. Ще питання по годині від'їзду — 09:30 на АЗС «Швидко», хтось спізниться — дзвонить Навігатору.",
      timestamp: new Date(Date.now() - 86400000 * 1 + 360000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-29",
      type: "text",
      content: "Погоджуюсь. Навігатор — ти, пам’ятай. Ідея: скину в чат «живу» фото місця пікніка вранці, щоб усі зрозуміли куди йти.",
      timestamp: new Date(Date.now() - 7200000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-30",
      type: "text",
      content: "Чудово. Ще на випадок дощу — запасний план: зустрічаємось під навісом в Точці B (X13-Y9), там дах і столики.",
      timestamp: new Date(Date.now() - 7000000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-31",
      type: "text",
      content: "Запасний план прийнято. Я ще кину одне голосове з координатами маршруту, щоб простіше було слухати інструкцію.",
      timestamp: new Date(Date.now() - 3600000 * 20),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-32",
      type: "voice",
      url: "https://example.com/voice/12sec.ogg",
      duration: 12,
      caption: "Голосове: коротко про маршрут Точка A → B",
      timestamp: new Date(Date.now() - 3600000 * 19),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-33",
      type: "text",
      content: "Прослухав, ок. Все ясно. Як щодо музичної підбірки? Хтось буде відповідати за колонки?",
      timestamp: new Date(Date.now() - 3600000 * 18),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-34",
      type: "text",
      content: "Я беру колонки. Є Bluetooth колонка силою, вистачить для невеликої галявини. Батарея на 8 годин.",
      timestamp: new Date(Date.now() - 3600000 * 17 + 60000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-35",
      type: "image",
      url: "https://picsum.photos/500/300?random=35",
      caption: "Колонка, яку беру — компактна, гучна.",
      timestamp: new Date(Date.now() - 3600000 * 16 + 120000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-36",
      type: "text",
      content: "Супер. Я візьму м’ясо та маринад, Маша — салати, Сергій — напої. Всі зручні?",
      timestamp: new Date(Date.now() - 3600000 * 15),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-37",
      type: "text",
      content: "Ок. Прохолодні напої в Фургоні-1. Пам'ятаємо про сміття — беремо мішки.",
      timestamp: new Date(Date.now() - 3600000 * 14 + 30000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-38",
      type: "text",
      content: "Погоджуюсь. Ще рекомендую взяти невеликий набір для фіксації: мотузка, скотч. Може знадобитись для тенту.",
      timestamp: new Date(Date.now() - 3600000 * 13),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-39",
      type: "text",
      content: "Додаю в чек-лист. До речі, Міша скинув фото свого мото — виглядає як новий, напишу побажання їхати обережно.",
      timestamp: new Date(Date.now() - 3600000 * 12 + 90000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-40",
      type: "image",
      url: "https://picsum.photos/800/450?random=40",
      caption: "Мото Міши — блискучий, як завжди.",
      timestamp: new Date(Date.now() - 3600000 * 11),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-41",
      type: "text",
      content: "Ха-ха, як новий! Ок, з приводу зустрічі: кидаю умовну інструкцію по підготовці колони (побутово).",
      timestamp: new Date(Date.now() - 3600000 * 10 + 60000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-42",
      type: "text",
      content: "Я слухаю. Що саме в інструкції?",
      timestamp: new Date(Date.now() - 3600000 * 9 + 30000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-43",
      type: "text",
      content: "1) Перевірити світло/повідомити про проблеми; 2) Закріпити багаж; 3) Встановити загальні сигнали; 4) Останній чек перед від’їздом — 10 хв.",
      timestamp: new Date(Date.now() - 3600000 * 9 + 90000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-44",
      type: "text",
      content: "Все ок. Додам пункт: перевірити наявність аптечки та намету (на випадок, якщо погода зіпсується).",
      timestamp: new Date(Date.now() - 3600000 * 8 + 120000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-45",
      type: "text",
      content: "Маю на увазі, що «колона» тут — просто дружня група транспорту для зручності. Нічого технічного, лише логістика для пікніка.",
      timestamp: new Date(Date.now() - 3600000 * 8 + 240000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-46",
      type: "text",
      content: "Зрозумів. Тобто — все побутово: хто що везе, де зустрічаємось, як рухатись. Умовні позначки — лише для зручності.",
      timestamp: new Date(Date.now() - 3600000 * 7 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-47",
      type: "text",
      content: "Саме так. Тепер про розподіл: Фургон-1 — стільці/мангал/напої; Машина-2 — страви; Мото — розвідка дороги (жарт).",
      timestamp: new Date(Date.now() - 3600000 * 7 + 180000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-48",
      type: "text",
      content: "Розвідка дороги — беру! Хоча в мене просто телефон з навігатором 😄",
      timestamp: new Date(Date.now() - 3600000 * 6 + 90000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-49",
      type: "image",
      url: "https://picsum.photos/700/500?random=49",
      caption: "Схема зустрічі на АЗС — позначив парковку для Фургона та для машин.",
      timestamp: new Date(Date.now() - 3600000 * 6 + 210000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-50",
      type: "text",
      content: "Класно. Ще одна дрібниця — хтось візьме газовий плиту на випадок, якщо сумні з мангалом? Просто запасний варіант.",
      timestamp: new Date(Date.now() - 3600000 * 5 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-51",
      type: "text",
      content: "Я можу взяти маленьку плитку. Вона в рюкзаку займає мало місця.",
      timestamp: new Date(Date.now() - 3600000 * 5 + 120000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-52",
      type: "text",
      content: "Чудово. Погодилися з часом та місцем. Залишилось домовитись про безпеку — вимикаємо різкі маневри і дбаємо про дітей/тварин, якщо вони з нами.",
      timestamp: new Date(Date.now() - 3600000 * 4 + 30000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-53",
      type: "text",
      content: "Так, безпека понад усе. Я нагадаю кожному перед виїздом у чаті. Можеш вкинути коротку інструкцію по сигналам ще раз?",
      timestamp: new Date(Date.now() - 3600000 * 4 + 150000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-54",
      type: "text",
      content: "Оновлюю: 1 короткий — піднімати швидкість/виїзд; 2 коротких — зупинка; 1 довгий — небезпека/стоп. Простий та зрозумілий код.",
      timestamp: new Date(Date.now() - 3600000 * 3 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-55",
      type: "voice",
      url: "https://example.com/voice/7sec.ogg",
      duration: 7,
      caption: "Голосове: нагадування про сигнали та час збору",
      timestamp: new Date(Date.now() - 3600000 * 3 + 120000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-56",
      type: "text",
      content: "Прослухав — все ок. Ще одне: де будемо паркуватись в Точці B? Мабуть біля старого сараю — там рівна площадка.",
      timestamp: new Date(Date.now() - 3600000 * 2 + 90000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-57",
      type: "text",
      content: "Так, біля сараю є місце, я його відмітив на карті. Якщо буде повно — заїдемо трохи далі, біля ставка є галявина.",
      timestamp: new Date(Date.now() - 3600000 * 2 + 180000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-58",
      type: "text",
      content: "Планую приїхати на годину раніше, щоб допомогти розташуватись. Можеш взяти на себе первинну організацію місця?",
      timestamp: new Date(Date.now() - 3600000 * 1 + 60000),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-59",
      type: "text",
      content: "Візьму. Поставлю тент, розкладні столи. Якщо хтось не знайде — я буду на Точці A з червоним прапорцем (жарт), або просто телефон.",
      timestamp: new Date(Date.now() - 3600000 * 1 + 150000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-60",
      type: "image",
      url: "https://picsum.photos/600/300?random=60",
      caption: "Тент для пікніка — компактний, але великий.",
      timestamp: new Date(Date.now() - 3600000 * 1 + 240000),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-61",
      type: "text",
      content: "І ще — фотографії/відео з пікніка будемо робити? Може хтось зніме таймлапс з Точки B?",
      timestamp: new Date(Date.now() - 3600000 * 0.8),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-62",
      type: "text",
      content: "Я візьму штатив і камеру для таймлапсу. Буде стильний ролик для вечірніх спогадів.",
      timestamp: new Date(Date.now() - 3600000 * 0.7),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-63",
      type: "text",
      content: "Круто. А щодо умовних «точок» — можеш підписати на карті ще Точку D для запасного паркування (X15-Y10)?",
      timestamp: new Date(Date.now() - 3600000 * 0.6),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-64",
      type: "text",
      content: "Додав. Тепер у нас Точки: A (старт), B (пікнік), C (об’їзд), D (запасне паркування). Всі умовні, лише для зручності.",
      timestamp: new Date(Date.now() - 3600000 * 0.5),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-65",
      type: "text",
      content: "Машина-3 просить останні інструкції по навантаженню — скільки стільців і столів беремо?",
      timestamp: new Date(Date.now() - 3600000 * 0.4),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-66",
      type: "text",
      content: "Стільців 10, столів 2. Плюс тент і кухня (мангал + плитка). Вага компактна, розподіли між двома авто.",
      timestamp: new Date(Date.now() - 3600000 * 0.3),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-67",
      type: "text",
      content: "Окей, розподілю багаж: машина-2 — столи/стільці; фургон — напої та запасні речі. Мото — лише для швидкого під'їзду.",
      timestamp: new Date(Date.now() - 3600000 * 0.2),
      isOutgoing: false,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-68",
      type: "image",
      url: "https://picsum.photos/800/400?random=68",
      caption: "Схематичне фото пакування — все має вміститись компактно.",
      timestamp: new Date(Date.now() - 3600000 * 0.15),
      isOutgoing: true,
      isRead: true,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-69",
      type: "text",
      content: "Ми майже на місці. Я заправив машину, перевірив шини і аптечку. Ще раз: 09:30 на АЗС.",
      timestamp: new Date(Date.now() - 720000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-70",
      type: "text",
      content: "Я теж виїжджаю з дому. Кидаю фото з маршруту коли в'їжджатиму в область Точка C.",
      timestamp: new Date(Date.now() - 600000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-71",
      type: "image",
      url: "https://picsum.photos/640/360?random=71",
      caption: "Дорога до Точки C — зараз нормальна, трохи ям, тримай швидкість",
      timestamp: new Date(Date.now() - 540000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-72",
      type: "text",
      content: "Отлично. Сергій пише, що Фургон-1 теж майже на АЗС. Вони будуть першим елементом нашої колони.",
      timestamp: new Date(Date.now() - 480000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-73",
      type: "text",
      content: "Пам’ятаємо сигнали. Кидай, якщо хтось відстає — двічі короткий сигнал.",
      timestamp: new Date(Date.now() - 420000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-74",
      type: "text",
      content: "Отримав. До речі, запропонував Місці взяти ще пару пледів — вечір може бути прохолодним.",
      timestamp: new Date(Date.now() - 360000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-75",
      type: "text",
      content: "Пледи — хороша ідея. Я візьму ще декілька одноразових тарілок і виделок.",
      timestamp: new Date(Date.now() - 300000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-76",
      type: "image",
      url: "https://picsum.photos/720/480?random=76",
      caption: "Фото пакування у фургоні — все складено щільно.",
      timestamp: new Date(Date.now() - 240000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-77",
      type: "text",
      content: "Чудово, виглядає як бойовий (але мирний) набір для пікніка 😄",
      timestamp: new Date(Date.now() - 200000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-78",
      type: "text",
      content: "Ха-ха, саме так. Я під'їхав до АЗС, поруч стою біля колонки №3. Хто ще?",
      timestamp: new Date(Date.now() - 160000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-79",
      type: "text",
      content: "Я заправляюсь, приблизно 5 хв і буду. Мото вже безлюдний, тому перша у черзі буде фургон.",
      timestamp: new Date(Date.now() - 120000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-80",
      type: "text",
      content: "Фургон на місці. Всім рацію: дві машини позаду. Рушимо хвилями — перший етап виїзд о 09:35.",
      timestamp: new Date(Date.now() - 90000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-81",
      type: "voice",
      url: "https://example.com/voice/9sec.ogg",
      duration: 9,
      caption: "Голосове: коротке «все ок, рушаємо»",
      timestamp: new Date(Date.now() - 60000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-82",
      type: "text",
      content: "Рушили. Я йду другим авто. Буду слідкувати за дистанцією.",
      timestamp: new Date(Date.now() - 45000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-83",
      type: "text",
      content: "Я за мото — буду триматися на відстані, щоб не створювати перешкод. Фото з дороги кину пізніше.",
      timestamp: new Date(Date.now() - 30000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-84",
      type: "text",
      content: "Заїхали на гірку поруч з Точкою A — краєвид огонь. Кину фото після розгортання табору.",
      timestamp: new Date(Date.now() - 20000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-85",
      type: "image",
      url: "https://picsum.photos/900/500?random=85",
      caption: "Вид з гірки — краєвид супер, думка була правильна.",
      timestamp: new Date(Date.now() - 15000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-86",
      type: "text",
      content: "Фух, паркуємось. Хто починає розгортати мангал? Я можу допомогти з розпалюванням.",
      timestamp: new Date(Date.now() - 12000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-87",
      type: "text",
      content: "Я з Мішею вже базую місце під тентом. Сергій займется мангалом. Дотримуємось вільного простору від дерев.",
      timestamp: new Date(Date.now() - 8000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-88",
      type: "text",
      content: "Я поставив колонки та штатив. Можемо запускати музичний сет через 10 хв.",
      timestamp: new Date(Date.now() - 6000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-89",
      type: "text",
      content: "Починаємо з приготування: хто знає, де сіль та приправи? Маша каже, що все в коробці «кухня».",
      timestamp: new Date(Date.now() - 4000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-90",
      type: "text",
      content: "Я маю сіль і перець, передаю їх Сергію. Хто візьме фото вечірки?",
      timestamp: new Date(Date.now() - 3000),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-91",
      type: "text",
      content: "Я зніматиму таймлапс, ще й розрахував місце для камери. Киньте мені ваші кумедні пози для фото 😄",
      timestamp: new Date(Date.now() - 2000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-92",
      type: "text",
      content: "Пози: 1) всі з мангалом; 2) групове селфі з колонкою; 3) мемна поза Міші на мото. Я за!",
      timestamp: new Date(Date.now() - 1500),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-93",
      type: "image",
      url: "https://picsum.photos/800/600?random=93",
      caption: "Перша проба мангалу — вогонь під контролем.",
      timestamp: new Date(Date.now() - 1000),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-94",
      type: "text",
      content: "Почали жарити — запах божественний. Хто бере фото з готовою тарілкою?",
      timestamp: new Date(Date.now() - 800),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-95",
      type: "text",
      content: "Я сфоткаю і кину в чат. Потім зберемося біля дуба для групової.",
      timestamp: new Date(Date.now() - 500),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-96",
      type: "image",
      url: "https://picsum.photos/720/480?random=96",
      caption: "Перша порція — можна їсти. Bon appetit!",
      timestamp: new Date(Date.now() - 400),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-97",
      type: "text",
      content: "Дякую всім за організацію — вийшло круто. Обов'язково зробимо це знову. Пропоную наступного разу Точку E (X16-Y11) — новий майданчик.",
      timestamp: new Date(Date.now() - 200),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-98",
      type: "text",
      content: "Погоджуюсь. Наступного разу я займусь десертом. А ще — перевіримо нові плани руху (умовні координати) заздалегідь.",
      timestamp: new Date(Date.now() - 120),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-99",
      type: "text",
      content: "Чудово. Вкінці дня підведемо підсумки: що було корисно в плануванні, а що можна покращити (чек-лист залишиться у чаті).",
      timestamp: new Date(Date.now() - 60),
      isOutgoing: false,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
    {
      id: "msg-1-100",
      type: "voice",
      url: "https://example.com/voice/9sec_end.ogg",
      duration: 9,
      caption: "Голосове: коротке спасибо всім, гарного вечора",
      timestamp: new Date(Date.now()),
      isOutgoing: true,
      isRead: false,
      status: "none",
      isBookmarked: false,
    },
  ],
};
